-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/user_secondary_email (
  use_id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
  use_cuid INTEGER UNSIGNED NOT NULL,
  use_email CLOB NOT NULL, use_email_authenticated BLOB DEFAULT NULL,
  use_email_token BLOB DEFAULT NULL,
  use_email_token_expires BLOB DEFAULT NULL
);

CREATE INDEX use_cuid ON /*_*/user_secondary_email (use_cuid);

CREATE INDEX use_email_token ON /*_*/user_secondary_email (use_email_token);

CREATE INDEX use_email ON /*_*/user_secondary_email (use_email);
