-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: MultiMail/sql/tables.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/user_secondary_email (
  use_id INT UNSIGNED AUTO_INCREMENT NOT NULL,
  use_cuid INT UNSIGNED NOT NULL,
  use_email TINYTEXT NOT NULL,
  use_email_authenticated BINARY(14) DEFAULT NULL,
  use_email_token BINARY(32) DEFAULT NULL,
  use_email_token_expires BINARY(14) DEFAULT NULL,
  INDEX use_cuid (use_cuid),
  INDEX use_email_token (use_email_token),
  INDEX use_email (
    use_email(50)
  ),
  PRIMARY KEY(use_id)
) /*$wgDBTableOptions*/;
